Module6 task1
htmlacademy-php/305355-readme-12 pull request #11
Opened 2021-12-22 14:47 UTC by k0t-pirat

2021-12-26 09:29 UTC, ademaro requested changes
Давай норм сделаем, что бы двигать дальше, пока не много изменений

2021-12-26 09:29 UTC, ademaro commented on index.php
> +$con = mysqli_connect('localhost', 'root', 'root', 'readme');
давай в конфиг какой-нибудь или инит)

2021-12-26 09:29 UTC, ademaro commented on index.php
> +if ($con == false) {
всегда используем строгое равенство

2021-12-26 09:29 UTC, ademaro commented on index.php
> +if ($con == false) {
или тут достаточно `if (!$con) {`

2021-12-26 09:29 UTC, ademaro commented on index.php
> +  $posts_result = mysqli_query($con, $posts_sql);
сделай две функции get_types() и get_posts() и давай их в models.php

2021-12-26 09:29 UTC, ademaro commented on index.php
> +  }
ошибку — в те ф-ции + можем шаблон сразу сделать для ошибки

2021-12-26 09:29 UTC, ademaro commented on post.php
> +$con = mysqli_connect('localhost', 'root', 'root', 'readme');
вот, пошли повторяться) надо в одном месте

2021-12-26 09:29 UTC, ademaro commented on post.php
> +  }
DRY

2021-12-26 09:29 UTC, ademaro commented on templates/main.php
>                                              <img src="https://www.google.com/s2/favicons?domain=vitadental.ru" alt="Иконка">
откуда vitadental.ru? это вам дали??

2021-12-26 10:12 UTC, k0t-pirat commented on templates/main.php
>                                              <img src="https://www.google.com/s2/favicons?domain=vitadental.ru" alt="Иконка">
я хз, если честно, вряд ли я что-то внутри ссылок менял

2022-06-19 16:07 UTC, ademaro commented
Вижу, что поправлено, но надо исправить конфликты слияния

2022-06-20 06:58 UTC, merged