Module4 task2
htmlacademy-php/305355-readme-12 pull request #8
Opened 2021-04-01 12:37 UTC by k0t-pirat

2021-04-04 13:54 UTC, ademaro commented on schema.sql
> +  title CHAR(128) NOT NULL,
давай разберёмся всё-таки в чём различие CHAR от VARCHAR и в каких полях что именно нам нужно)

2021-04-04 13:54 UTC, ademaro commented on schema.sql
> +  password CHAR(128) NOT NULL,
Почему всё-таки 128?)

2021-04-04 13:57 UTC, ademaro requested changes
Давай тогда со структурой полностью закроем вопрос и отправимся дальше

2021-07-27 05:38 UTC, k0t-pirat commented
CHAR всегда имеют фиксированную длину, заданную в схеме таблицы, если строка меньше по длине, чем в схеме таблицы, то CHAR дополняется пробелами. VARCHAR в этом случае будет занимать место, равное длине строки, а не заданное в схеме. Кроме того VARCHAR может хранить дополнительные пробелы в строке, а CHAR - нет, так как CHAR дополняет строку пробелами до нужной длины и не знает о количестве пробелов  в конце строки. Так же VARCHAR может быть длины до 65535, а CHAR - 255 символов + VARCHAR хранит дополнительный 1 или 2 байта со значением длины строки. Как правило следует использовать VARCHAR, чтобы не расходовать лишнюю память, но если известно, что длина строки всегда фиксировнная, а так же в некоторых других случаях стоит использовать CHAR, так как он немного быстрее.

2021-07-27 05:42 UTC, k0t-pirat commented
В основном я решил использовать VARCHAR длины 255, для некоторых полей - 128, например, title, так как посчитал 255 избыточным, для e-mail я использовал VARCHAR длины 320 (64 для имени пользователя, 1 для @, 255 для доменного имени). Для пароля я решил использовать CHAR длины 128, так как решил, что CHAR с фиксированной длиной будет безопаснее.

2021-07-27 13:24 UTC, ademaro approved these changes

2021-07-27 13:25 UTC, merged